// Generated by CoffeeScript 1.6.2
(function() {
  var defaultHandlers, html_entities, html_escape, html_escaper, js_escape, js_escapeSequences, js_escaper, template, toSource;

  html_entities = {
    '<': '&lt;',
    '>': '&gt;',
    '&': '&amp;',
    '"': '&quot;',
    "'": '&#x27;',
    '/': '&#x2F;'
  };

  html_escaper = function(c) {
    return html_entities[c];
  };

  html_escape = function(s) {
    return s.replace(/[<>&'"\/]/g, html_escaper);
  };

  js_escapeSequences = {
    "'": "\\'",
    '\\': '\\\\',
    '\r': '\\r',
    '\n': '\\n',
    '\t': '\\t',
    '\u2028': '\\u2028',
    '\u2029': '\\u2029'
  };

  js_escaper = function(c) {
    return js_escapeSequences[c];
  };

  js_escape = function(s) {
    return s.replace(/\\|'|\r|\n|\t|\u2028|\u2029/g, js_escaper);
  };

  toSource = function(tmplSource, handlers) {
    var fnSource, handler, index, matcher, matcher_s, _i, _len;

    if (handlers == null) {
      handlers = defaultHandlers;
    }
    matcher_s = '';
    for (_i = 0, _len = handlers.length; _i < _len; _i++) {
      handler = handlers[_i];
      matcher_s += handler.regex.source + '|';
    }
    matcher_s += '$';
    matcher = new RegExp(matcher_s, 'g');
    fnSource = "var _muT_out='";
    index = 0;
    tmplSource.replace(matcher, function() {
      var argNum, currentMatch, match, offset, _j, _ref;

      match = arguments[0];
      offset = arguments[arguments.length - 2];
      fnSource += js_escape(tmplSource.slice(index, offset));
      for (argNum = _j = 0, _ref = handlers.length - 1; 0 <= _ref ? _j <= _ref : _j >= _ref; argNum = 0 <= _ref ? ++_j : --_j) {
        currentMatch = arguments[argNum + 1];
        if (currentMatch) {
          fnSource = handlers[argNum].handler(fnSource, currentMatch);
          break;
        }
      }
      index = offset + match.length;
      return match;
    });
    fnSource += "'; return _muT_out;";
    return fnSource;
  };

  defaultHandlers = [
    {
      regex: /\{\{([\s\S]+?)\}\}/,
      handler: function(fnSource, jsCode) {
        return fnSource + ("'; " + jsCode + " ; _muT_out+='");
      }
    }, {
      regex: /\{=([\s\S]+?)\}/,
      handler: function(fnSource, unescaped) {
        return fnSource + ("' + " + unescaped + " + '");
      }
    }, {
      regex: /\{([\s\S]+?)\}/,
      handler: function(fnSource, escaped) {
        return fnSource + ("' + muT.html_escape('' + " + escaped + ") + '");
      }
    }
  ];

  template = function(tmplSource, argNames, handlers) {
    var args, fnSource;

    if (argNames == null) {
      argNames = [];
    }
    if (handlers == null) {
      handlers = defaultHandlers;
    }
    fnSource = toSource(tmplSource, handlers);
    args = argNames.concat([fnSource]);
    return Function.apply(null, args);
  };

  window.muT = {
    html_escape: html_escape,
    js_escape: js_escape,
    toSource: toSource,
    defaultHandlers: defaultHandlers,
    template: template
  };

}).call(this);
